load_error: accept a filesystem::path, not a string
This prevents non-portable implicit conversions to strings, which
cause problems with icx.

See https://www.reddit.com/r/cpp/comments/su1atm/shouldnt_pathoperator_string_type_be_explicit/
for (an example of) a discussion about this.